### ISSUE TITLE
Back to main page with query stored

### ISSUE THREAD

**Issue by fsharpasharp** [fysikteknologsektionen/chalmers-course-stats#20]
Currently the page navigation is not satisfactory. After clicking a course there is no button to go back to the main page. Using the browser's back function also results in the previous query not being stored. Solve this by saving the previous query and adding a button or link to go back to the main page from the detailed course view.

**Comment by JohanWinther** [comment]
I cannot reproduce the previous queries not being stored. What are the steps?

**Comment by fsharpasharp** [comment]
1. Start at the main page.
2. Type in a string and change sorting order
3. Press a course code
4. Press back
5. Previous query is not saved
