### ISSUE TITLE
Chalmers Excel document with results is gone

### ISSUE THREAD

**Issue by JohanWinther** [fysikteknologsektionen/chalmers-course-stats#39]
The [Excel document](https://document.chalmers.se/doc/00000000-0000-0000-0000-00001C968DC6) is not available.

**Comment by JohanWinther** [comment]
Further communication on this issue will be in Swedish.

Jag har börjat diskussioner med [SNF](https://ftek.se/snf/) om hur vi ska gå tillväga för att kontinuerligt få tag på denna information, helst per automatik. Vi får helt enkelt se vad det leder till.

**Comment by JohanWinther** [comment]
Tydligen kommer inte filen att publiceras publikt längre, men man kan höra av sig manuellt för att få tag på filen. Kan man skapa ett automatiserat mailskript som frågar efter filen och laddar in den vid svar? @fsharpasharp

**Comment by martindue** [comment]
Jag har haft en mailkonversation med utbildningssekreteraren. Här är ett utdrag ur den:

> Tyvärr så finns ingen sådan statistik längre. När nya Ladok infördes försvann möjligheten att få fram dessa data. Det var helt oförutsett, när vi frågade leverantören fick vi i svaret att ”det ingick inte i kravspecifikationen när ni beställde systemet”. Naturligtvis är vi inte nöjda med det svaret men vi har ännu inte fått någon lösning på detta. Den centrala Ladokgruppen på Chalmers kan inte få fram det på något annat sätt heller. Vi hoppas fortfarande att det kan gå att ordna.

Jag har bett honom maila oss om läget förändras.
